---
# Fill in vars.yml before running

# Post-provisioning VM
- name: "Provision Enviorment"
  strategy: linear
  hosts: all
  become: true
  vars_files:
    - vars/vars.yml
    - vars/vault.yml
  tasks:

  - name: Collect Server IP
    debug:
      msg: "{{ ansible_ssh_host }}"
      
  - name: Install Docker from official signed repo
    when: install_docker == true
    include: tasks/docker.yml

  - name: Install Server
    tags:
      - mc_server
    include: tasks/minecraft_server.yml

  - name: Restart MC Server
    tags:
      - restart_mc_server
    include: tasks/admin_tasks.yml

  - name: Restart MC Server
    tags:
      - backup_world
    include: tasks/backups.yml

  - name: Deploy Web Server
    tags:
      - deploy_web_server
    include: tasks/web_server.yml
    