---
# Fill in vars.yml before running

# Post-provisioning VM
- name: "Provision Enviorment"
  strategy: linear
  hosts: all
  become: true
  vars_files:
    - vars/vars.yml
    - vars/vault.yml
  tasks:

  - name: Collect Server IP
    debug:
      msg: "{{ ansible_ssh_host }}"
      
  - name: Install Docker from official signed repo
    when: install_docker == true
    include: tasks/docker.yml

  - name: Install Required Packages
    include: tasks/minecraft_server.yml
    