- name: Restart Container
  tags:
  - restart_mc_server
  shell: "sudo docker restart {{HOSTNAME}}"

- name: Execute RCON
  tags:
  - rcon_cmd
  shell: "docker exec {{HOSTNAME}} rcon-cli op {{item}}"

