- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{homedir}}/container-program-files/fileserver_share_files/minecraft-server_backups"
    state: directory
    mode: '0755'

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{homedir}}/container-program-files/fileserver_share_files/minecraft-server_backups/{{ansible_date_time.date}}"
    state: directory
    mode: '0755'

- name: Backup World
  tags:
  - backup_world
  shell: "cp -r {{homedir}}/container-program-files/fileserver_share_files/minecraft-server/world {{homedir}}/container-program-files/fileserver_share_files/minecraft-server_backups/{{ansible_date_time.date}}/world"
  ignore_errors: true

- name: Backup World Nether
  tags:
  - backup_world
  shell: "cp -r {{homedir}}/container-program-files/fileserver_share_files/minecraft-server/world_nether {{homedir}}/container-program-files/fileserver_share_files/minecraft-server_backups/{{ansible_date_time.date}}/world_nether"
  ignore_errors: true

- name: Backup World The End
  tags:
  - backup_world
  shell: "cp -r {{homedir}}/container-program-files/fileserver_share_files/minecraft-server/world_nether {{homedir}}/container-program-files/fileserver_share_files/minecraft-server_backups/{{ansible_date_time.date}}/world_the_end"
  ignore_errors: true