- name: Prep backup folder
  tags:
  - backup_world
  shell: "mkdir {{homedir}}/container-program-files/fileserver_share_files/minecraft-server_backups/{{ansible_date_time.date}}"
  ignore_errors: true
  
- name: Backup World
  tags:
  - backup_world
  shell: "cp -r {{homedir}}/container-program-files/fileserver_share_files/minecraft-server/world {{homedir}}/container-program-files/fileserver_share_files/minecraft-server_backups/{{ansible_date_time.date}}/world"
  ignore_errors: true

- name: Backup World Nether
  tags:
  - backup_world
  shell: "cp -r {{homedir}}/container-program-files/fileserver_share_files/minecraft-server/world_nether {{homedir}}/container-program-files/fileserver_share_files/minecraft-server_backups/{{ansible_date_time.date}}/world_nether"
  ignore_errors: true

- name: Backup World The End
  tags:
  - backup_world
  shell: "cp -r {{homedir}}/container-program-files/fileserver_share_files/minecraft-server/world_nether {{homedir}}/container-program-files/fileserver_share_files/minecraft-server_backups/{{ansible_date_time.date}}/world_the_end"
  ignore_errors: true