- name: mc.branconet.com
  tags:
    - deploy_web_server
  docker_container:
    name: "ws-mc.branconet.com"
    image: "nginx"
    pull: yes
    state: started
    restart: yes
    restart_policy: unless-stopped
    ports: 
      - "{{ target_server_ip }}:8080:80"
    volumes:
      - '{{homedir}}/container-program-files/ws-mc.branconet.com:/usr/share/nginx/html'

- name: Clone mc.branconet.com
  tags:
    - deploy_web_server
  ansible.builtin.git:
    repo: https://github.com/jtmb/minecraft-html.git
    dest: '{{homedir}}/container-program-files/ws-mc.branconet.com'
    version: master

- name: Restart mc.branconet.com
  tags:
    - deploy_web_server
  shell: docker restart ws-mc.branconet.com